"""
Django settings for _20250723django project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # os 모듈 임포트 (MEDIA_ROOT 설정에 필요)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@e02c52n(g9+v&p0^h3#%e#f2%n_d=w@p75^o3#*w^3a68+3c&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taggit', # django-taggit 앱 등록
    'home.apps.HomeConfig', # home 앱 등록
    'bookmark.apps.BookmarkConfig', # bookmark 앱 등록
    'blog.apps.BlogConfig', # blog 앱 등록
    'photo.apps.PhotoConfig', # photo 앱 등록 (PhotoConfig 클래스 사용)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_20250723django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 모든 템플릿을 이 프로젝트 전역 폴더에서 찾도록 설정
        'APP_DIRS': True, # 각 앱 내부의 'templates' 폴더는 더 이상 자동으로 탐색하지 않음
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = '_20250723django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr' # 한국어로 설정

TIME_ZONE = 'Asia/Seoul' # 서울 시간대로 설정

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static',] # STATICFILES_DIRS 설정 (pathlib 스타일)

# Media files (User uploaded files)
# 사용자가 업로드한 파일을 위한 설정
MEDIA_URL = '/media/' # 웹에서 미디어 파일에 접근할 URL 접두사
MEDIA_ROOT = BASE_DIR / 'media' # 업로드된 파일이 저장될 실제 파일 시스템 경로 (pathlib 스타일)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 로그인 성공 후 리다이렉트될 URL (인증 기능 구현 시 사용)
# LOGIN_REDIRECT_URL = '/' # 홈페이지로 리다이렉트
# LOGOUT_REDIRECT_URL = '/' # 로그아웃 후 홈페이지로 리다이렉트

