# Generated by Django 5.2.4 on 2025-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_category_alter_bookmark_options_bookmark_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명/메모'),
        ),
    ]
