# Generated by Django 5.2.4 on 2025-07-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='썸네일 URL'),
        ),
    ]
