# Generated by Django 5.2.4 on 2025-07-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
    ]
